/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BlockDirectus: typeof import('./components/_blocks/BlockDirectus.vue')['default']
    BlockFeatures: typeof import('./components/_blocks/BlockFeatures.vue')['default']
    BlockHero: typeof import('./components/_blocks/BlockHero.vue')['default']
    HeroBlock: typeof import('./components/_blocks/HeroBlock.vue')['default']
    MrxAppBar: typeof import('./components/_core/MrxAppBar.vue')['default']
    MrxPasswordField: typeof import('./components/_core/MrxPasswordField.vue')['default']
    Navigation: typeof import('./components/_core/Navigation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SqlVendors: typeof import('./components/_ui/SqlVendors.vue')['default']
  }
}
