/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./components/_ui/AppButton.vue')['default']
    AppFormGroup: typeof import('./components/_ui/AppFormGroup.vue')['default']
    ContactForm: typeof import('./components/_core/ContactForm.vue')['default']
    IndexAbout: typeof import('./components/_sections/index/IndexAbout.vue')['default']
    IndexArticles: typeof import('./components/_sections/index/IndexArticles.vue')['default']
    IndexHero: typeof import('./components/_sections/index/IndexHero.vue')['default']
    IndexImpressions: typeof import('./components/_sections/index/IndexImpressions.vue')['default']
    IndexServices: typeof import('./components/_sections/index/IndexServices.vue')['default']
    IndexTestimonials: typeof import('./components/_sections/index/IndexTestimonials.vue')['default']
    Logo: typeof import('./components/_core/Logo.vue')['default']
    LogoSmall: typeof import('./components/_core/LogoSmall.vue')['default']
    NavBar: typeof import('./components/_core/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimplePage: typeof import('./components/SimplePage.vue')['default']
    TitlePage: typeof import('./components/TitlePage.vue')['default']
    VBtn: typeof import('./components/_ui/VBtn/VBtn.vue')['default']
    VSpinner: typeof import('./components/_ui/VSpinner/VSpinner.vue')['default']
  }
}
